id = "csharp-snippets"
name = "C# Snippets"
version = "0.0.0"
schema_version = 1
authors = ["Kenneth Joshua Becaro <joshuabecaro@gmail.com>"]
description = "C# snippets for Zed IDE."
repository = "" TODO
snippets = "" TODO